// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCell = "cell"

// Cell 单元格数据表
type Cell struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SheetID        int64     `gorm:"column:sheet_id;not null;comment:所属工作表ID" json:"sheet_id"`        // 所属工作表ID
	RowIndex       int32     `gorm:"column:row_index;not null;comment:行号（从1开始）" json:"row_index"`     // 行号（从1开始）
	ColIndex       int32     `gorm:"column:col_index;not null;comment:列号（从1开始）" json:"col_index"`     // 列号（从1开始）
	ItemID         *int64     `gorm:"column:item_id;comment:关联的可拖放元素ID" json:"item_id"`                // 关联的可拖放元素ID
	LastModifiedBy int64     `gorm:"column:last_modified_by;comment:最后修改者ID" json:"last_modified_by"` // 最后修改者ID
	Version        int32     `gorm:"column:version;not null;default:1;comment:版本号" json:"version"`    // 版本号
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeletedTime    gorm.DeletedAt     `gorm:"column:deleted_time" json:"deleted_time"`
}

// TableName Cell's table name
func (*Cell) TableName() string {
	return TableNameCell
}
