// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameClass = "class"

// Class 班级表:存储班级信息
type Class struct {
	ID         	int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"` // 自增主键
	Name       	string    `gorm:"column:name;not null;comment:班级名称" json:"name"`                  // 班级名称
	CreateTime 	time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime 	time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeletedTime gorm.DeletedAt     `gorm:"column:deleted_time" json:"deleted_time"`
}

// TableName Class's table name
func (*Class) TableName() string {
	return TableNameClass
}
