// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDraggableItem = "draggable_item"

// DraggableItem 可拖放元素库
type DraggableItem struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content    string    `gorm:"column:content;not null;comment:课程名称" json:"content"`             // 课程名称
	WeekType   string    `gorm:"column:week_type;not null;comment:周类型：单周/双周/全上" json:"week_type"` // 周类型：单周/双周/全上
	Classroom  string    `gorm:"column:classroom;not null;comment:上课教室" json:"classroom"`         // 上课教室
	CreatorID  int64     `gorm:"column:creator_id;not null;comment:创建者ID" json:"creator_id"`      // 创建者ID
	Teacher    string    `gorm:"column:teacher;not null;comment:任课老师" json:"teacher"`             // 任课老师
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime int64     `gorm:"column:delete_time" json:"delete_time"`
}

// TableName DraggableItem's table name
func (*DraggableItem) TableName() string {
	return TableNameDraggableItem
}
