// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDraggableItemClass = "draggable_item_class"

// DraggableItemClass 元素-班级关联表
type DraggableItemClass struct {
	ItemID  int64 `gorm:"column:item_id;primaryKey;comment:可拖动元素ID" json:"item_id"`  // 可拖动元素ID
	ClassID int64 `gorm:"column:class_id;primaryKey;comment:班级课表ID" json:"class_id"` // 班级课表ID
}

// TableName DraggableItemClass's table name
func (*DraggableItemClass) TableName() string {
	return TableNameDraggableItemClass
}
