// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDraggableClassSheet = "draggable_class_sheet"

// DraggableClassSheet 元素-课表关联表
type DraggableClassSheet struct {
	ItemID  int64 `gorm:"column:item_id;primaryKey;comment:可拖动元素ID" json:"item_id"` // 可拖动元素ID
	ClassID int64 `gorm:"column:class_id;primaryKey;comment:班级ID" json:"class_id"`  // 班级ID
}

// TableName DraggableClassSheet's table name
func (*DraggableClassSheet) TableName() string {
	return TableNameDraggableClassSheet
}
