// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSheet = "sheet"

// Sheet 工作表主表
type Sheet struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`        // 自增主键
	Name       string    `gorm:"column:name;not null;comment:工作表名称" json:"name"`                        // 工作表名称
	Week       int32     `gorm:"column:week;not null;comment:周数" json:"week"`                           // 周数
	Row       int32     `gorm:"column:row;not null;comment:行数" json:"row"`                             // 行数
	Col        int32     `gorm:"column:col;not null;comment:列数" json:"col"`                             // 列数
	CreatorID  int64     `gorm:"column:creator_id;not null;comment:创建者ID（关联user.id）" json:"creator_id"` // 创建者ID（关联user.id）
	ClassID    int64     `gorm:"column:class_id;not null;comment:班级ID（关联class.id）" json:"class_id"`     // 班级ID（关联class.id）
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeletedTime    gorm.DeletedAt     `gorm:"column:deleted_time" json:"deleted_time"`
}

// TableName Sheet's table name
func (*Sheet) TableName() string {
	return TableNameSheet
}
